num = int(input('Digite um número, e te direi a tabuada dele: '))
print(f'{num} * 1 = {num*1}')
print(f'{num} * 2 = {num*2}')
print(f'{num} * 3 = {num*3}')
print(f'{num} * 4 = {num*4}')
print(f'{num} * 5 = {num*5}')
print(f'{num} * 6 = {num*6}')
print(f'{num} * 7 = {num*7}')
print(f'{num} * 8 = {num*8}')
print(f'{num} * 9 = {num*9}')
print(f'{num} * 10 = {num*10}')
cor = str(input('Correto? '))
if cor.capitalize() == 'Sim':
    print('Obrigado pelo Feedback!')
else:
    print('Entendido, desculpe-me pela falha, ela será corrigida.\nTenha um bom dia!')
